[package]
name = "gandi-rust-dns-updater"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

reqwest = "0.11.7"
toml = "0.5.8"
serde = { version = "1.0", features = ["derive"] }
