[package]
name = "gandi-rust-dns-updater"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

reqwest = { version = "0.11.7", features = ["json"] }
toml = "0.5.8"
serde = { version = "1.0", features = ["derive"] }
directories = "4.0.1"
structopt = "0.3.25"
tokio = { version = "1.14.0", features = ["full"] }
