[package]
name = "gandi-live-dns"
version = "1.0.1"
edition = "2021"

[profile.release]
strip = "symbols"
lto = true

[dependencies]

reqwest = { version = "0.11.7", default-features= false, features = ["json", "rustls-tls"] }
toml = "0.5.8"
json = "0.12.4"
serde = { version = "1.0", features = ["derive"] }
directories = "4.0.1"
structopt = "0.3.25"
tokio = { version = "1.14.0", features = ["full"] }
futures = "0.3.17"
anyhow = "1.0"
# TODO: Relies on a yet-unreleased interface. Switch to an actual crate release once available
die-exit = { git = "https://github.com/Xavientois/die.git", rev = "31d3801f4e21654b0b28430987b1e21fc7728676" }
